common/models/WidgetSlider.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "widget_slider".
 *
 * @property int $id
 * @property string $name
 * @property int $created_at
 */
class WidgetSlider extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'widget_slider';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['created_at'], 'integer'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'created_at' => 'Дата создания',
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->created_at = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}

backend/controllers/WidgetSliderController.php
<?php

namespace backend\controllers;

use backend\models\ImageForm;
use common\models\WidgetSliderImage;
use Yii;
use common\models\WidgetSlider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * WidgetSliderController implements the CRUD actions for WidgetSlider model.
 */
class WidgetSliderController extends Controller
{
    public $scheme = 'widget_slider';
    public $image_model = WidgetSliderImage::class;
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $image = new ImageForm();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        if ($image->load(Yii::$app->request->post())) {

            if ($_FILES){
                Yii::$app->imageHelper->saveImageMultiple($image, $this->scheme, $this->image_model, $model->id);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'image' => $image,
        ]);
    }

    public function actionImageList($model_id)
    {
        $image_list = $this->image_model::findAll([$this->scheme . '_id' => $model_id]);

        return $this->renderPartial('image_list', [
            'image_list' => $image_list,
            'scheme' => $this->scheme,
        ]);
    }

    public function actionDeleteImage($id)
    {
        $image = $this->image_model::findOne($id);
        if ($image){
            Yii::$app->imageHelper->deleteImage($image->image, $this->scheme);
            $image->delete();
        }
    }

    public function actionSaveImageData()
    {

        if (Yii::$app->request->isAjax) {
            $data = Yii::$app->request->get();
            $image = $this->image_model::findOne($data['id']);
            $image->load($data, '');
            $image->save();
        }
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModel($id)
    {
        if (($model = WidgetSlider::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/widget-slider/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\WidgetSlider */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="widget-slider-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name_ru')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'name_en')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/widget-slider/image.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;


Pjax::begin();

$get_image_list = Url::to(["widget-slider/image-list"]);
$delete_image = Url::to(["widget-slider/delete-image"]);
$id = $model->id;
$save_image_name = Url::to(["widget-slider/save-image-data"]);

$script = <<< JS

    function getImageList() {        
        $.ajax({
            url: '$get_image_list',
            cache: false,
            type: "GET",
            data: { 'model_id': $id},
            success: function (data) {
                $('.image-list').html(data);
            }
        });
    }
    
    getImageList();

    $('.image-list').on('click', '.delete-image', function() { 
        $.ajax({
            url: '$delete_image',
            cache: false,
            type: "GET",
            data: { 'id': $(this).data('id')},
            success: function (data) {
                getImageList();
            }
        });
    });

    $('.image-list').on('keyup', "input[name='image-title']", function() { 
        $.ajax({
            url: '$save_image_name',
            cache: false,
            type: "GET",
            data: { 'id': $(this).data('id'), 'title': $(this).val()},
            success: function (data) {
                //getImageList();
            }
        });
    });
JS;
$this->registerJs($script, yii\web\View::POS_READY);

$form = ActiveForm::begin(['options' => ['data-pjax' => true, 'enctype' => 'multipart/form-data']]);
?>

<?= $form->field($image, 'image[]')->fileInput(['multiple' => true, 'accept' => 'image/*']) ?>

<div class="form-group">
    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
</div>

<?php ActiveForm::end(); ?>
<?php Pjax::end(); ?>

<div class="image-list">

</div>

backend/views/widget-slider/image_list.php
<?php

use rmrevin\yii\fontawesome\FA;
use yii\helpers\Html;
?>
    <style>
        .image{
            position: relative;
            margin: 15px;
            display: inline-block;
        }
        .image .delete-image{
            position: absolute;
            right: -13px;
            top: -13px;
            opacity: 0;
            transition: all .15s linear;
        }
        .image:hover .delete-image{
            opacity: .7;
        }
        .image:hover .delete-image:hover{
            opacity: 1;
        }
    </style>
<?php foreach ($image_list as $item):?>
    <div class="image">
        <?=Html::a(
            Html::img(
                Yii::$app->dataHelper->imageWebPath($scheme) . 'thumb_' . $item->image,
                [
                    'class' => 'img-thumbnail scheme-image',
                    'width' => 280
                ]
            ),
            Yii::$app->dataHelper->imageWebPath($scheme) . $item->image,
            [
                'data-lightbox' => 'big-image',
                'data-title' => '',
                'data-desc' => '',
            ]
        )?>
        <?=Html::button(FA::icon('remove'), [
            'class' => 'delete-image btn btn-danger',
            'data-id' => $item->id,
            'title' => 'Удалить',
            /*'data' => [
                'confirm' => 'Точно удалить?',
            ],*/
        ])?>
        <?=Html::input('text', 'image-title', $item->title_ru, [
            'class' => 'form-control',
            'data-id' => $item->id
        ])?>
    </div>
<?php endforeach; ?>

backend/views/widget-slider/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\WidgetSlider */

$this->title = 'Редактировать обьект: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Обьекты', 'url' => ['index']];
$this->params['breadcrumbs'][] =  $model->name;
?>
<div class="widget-slider-update">
    <br>
    <?php include 'image.php'?>

</div>