backend/controllers/ObjectController.php
<?php

namespace backend\controllers;

use backend\models\ImageForm;
use common\models\ObjectImage;
use Yii;
use common\models\MyObject;
use common\models\MyObjectSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * ObjectController implements the CRUD actions for MyObject model.
 */
class ObjectController extends Controller
{
    public $scheme = 'object';
    public $image_model = ObjectImage::class;
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $searchModel = new MyObjectSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreate()
    {
        $model = new MyObject();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['update', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $image = new ImageForm();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['update', 'id' => $model->id]);
        }

        if ($image->load(Yii::$app->request->post())) {

            if ($_FILES){
                Yii::$app->imageHelper->saveImageMultiple($image, $this->scheme, $this->image_model, $model->id);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'image' => $image,
        ]);
    }

    public function actionImageList($model_id)
    {
        $image_list = $this->image_model::find()->where([$this->scheme . '_id' => $model_id])->orderBy('sort')->all();

        return $this->renderPartial('image_list', [
            'image_list' => $image_list,
            'scheme' => $this->scheme,
        ]);
    }

    public function actionDeleteImage($id)
    {
        $image = $this->image_model::findOne($id);
        if ($image){
            Yii::$app->imageHelper->deleteImage($image->image, $this->scheme);
            $image->delete();
        }
    }

    public function actionSortImages()
    {
        $data = Yii::$app->request->post();
        foreach ($data['images'] as $key => $value) {
            $this->image_model::updateAll(['sort' => $key], ['id' => $value]);
        }
        return print_r($data);
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the MyObject model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return MyObject the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = MyObject::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/object/_form.php
<?php

use vova07\imperavi\Widget;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Object */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="object-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'category_id')
        ->dropDownList(
                \yii\helpers\ArrayHelper::map(\common\models\Category::find()->all(), 'id', 'name_ru'),
                ['prompt' => 'Выберите категорию']
        ) ?>

    <?= $form->field($model, 'name_ru')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'name_en')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description_ru')->widget(Widget::class, [
        'settings' => [
            'lang' => 'ru',
            'minHeight' => 200,
            'plugins' => [
                'clips',
                'fullscreen',
            ],
        ],
    ]);
    ?>

    <?= $form->field($model, 'description_en')->widget(Widget::class, [
        'settings' => [
            'lang' => 'ru',
            'minHeight' => 200,
            'plugins' => [
                'clips',
                'fullscreen',
            ],
        ],
    ]);
    ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/object/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Object */

$this->title = 'Создать обьект';
$this->params['breadcrumbs'][] = ['label' => 'Обьекты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="object-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/object/image.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;


Pjax::begin();

$get_image_list = Url::to(["object/image-list"]);
$delete_image = Url::to(["object/delete-image"]);
$sort_images = Url::to(["object/sort-images"]);
$param = Yii::$app->getRequest()->csrfParam;
$token = Yii::$app->getRequest()->getCsrfToken();
$id = $model->id;

$script = <<< JS

    function getImageList() {        
        $.ajax({
            url: '$get_image_list',
            cache: false,
            type: "GET",
            data: { 'model_id': $id},
            success: function (data) {
                $('.image-list').html(data);
            }
        });
    }
    
    getImageList();

    $('.image-list').on('click', '.delete-image', function() { 
        $.ajax({
            url: '$delete_image',
            cache: false,
            type: "GET",
            data: { 'id': $(this).data('id')},
            success: function (data) {
                getImageList();
            }
        });
    });
    
    $(".image-list").sortable({
        items:".image",
        update: function (event, ui) {
            var data = {
                'images': $(this).sortable('toArray'), 
                "{$param}": '$token', 
            };
            console.log(data);
            $.ajax({
                url: '$sort_images',
                type: 'POST',
                data: data,
                success: function (data) {
                    console.log(data);
                }
            });
        }
    });
JS;
$this->registerJs($script, yii\web\View::POS_READY);

$form = ActiveForm::begin(['options' => ['data-pjax' => true, 'enctype' => 'multipart/form-data']]);
?>

<?= $form->field($image, 'image[]')->fileInput(['multiple' => true, 'accept' => 'image/*']) ?>

<div class="form-group">
    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
</div>

<?php ActiveForm::end(); ?>
<?php Pjax::end(); ?>

<div class="image-list">

</div>

backend/views/object/image_list.php
<?php

use rmrevin\yii\fontawesome\FA;
use yii\helpers\Html;
?>
    <style>
        .image{
            position: relative;
            margin: 15px;
            display: inline-block;
        }
        .image .delete-image{
            position: absolute;
            right: -13px;
            top: -13px;
            opacity: 0;
            transition: all .15s linear;
        }
        .image:hover .delete-image{
            opacity: .7;
        }
        .image:hover .delete-image:hover{
            opacity: 1;
        }
    </style>
<?php foreach ($image_list as $item):?>
    <div class="image">
        <?=Html::a(
            Html::img(
                Yii::$app->dataHelper->imageWebPath($scheme) . 'thumb_' . $item->image,
                [
                    'class' => 'img-thumbnail scheme-image',
                    'width' => 280
                ]
            ),
            Yii::$app->dataHelper->imageWebPath($scheme) . $item->image,
            [
                'data-lightbox' => 'big-image',
                'data-title' => '',
                'data-desc' => '',
            ]
        )?>
        <?=Html::button(FA::icon('remove'), [
            'class' => 'delete-image btn btn-danger',
            'data-id' => $item->id,
            'title' => 'Удалить',
            /*'data' => [
                'confirm' => 'Точно удалить?',
            ],*/
        ])?>
    </div>
<?php endforeach; ?>

backend/views/object/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\ObjectSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Обьекты';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="object-index">

    <p class="text-right">
        <?= Html::a('Создать обьект', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],

            'id',
            'name_ru',
            [
                'attribute' => 'category_id',
                'format' => 'raw',
                'value' => function ($model) {
                    return $model->category ? $model->category->name_ru : '';
                },
                'filter' => \yii\helpers\ArrayHelper::map(\common\models\Category::find()->all(), 'id', 'name_ru'),
            ],
            //'meta_k',
            //'description:ntext',
            //'created_at',
            //'updated_at',

            [
                'class' => 'yii\grid\ActionColumn',
                'header'=>'Действия&nbsp;&nbsp;&nbsp;',
                'headerOptions' => ['width' => '90'],
                'template' => '{update}&nbsp;{delete}',
                'buttons' => [
                    'update' => function($url, $model){
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['update', 'id' => $model->id], [
                            'class' => 'btn btn-primary btn-sm',
                            'title' => 'Редактировать',
                        ]);
                    },
                    'view' => function($url, $model){
                        return Html::a('<span class="fa fa-eye"></span>', ['view', 'id' => $model->id], [
                            'class' => 'btn btn-success btn-sm',
                            'title' => 'View',
                        ]);
                    },
                    'delete' => function($url, $model){
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['delete', 'id' => $model->id], [
                            'class' => 'btn btn-danger btn-sm',
                            'title' => 'Удалить',
                            'data' => [
                                'confirm' => 'Точно удалить?',
                                'method' => 'post',
                            ],
                        ]);
                    }
                ],
            ],
        ],
    ]); ?>
</div>

backend/views/object/update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model common\models\Object */
/* @var $image common\models\Object */

$this->title = 'Редактировать обьект: ' . $model->name_ru;
$this->params['breadcrumbs'][] = ['label' => 'Обьекты', 'url' => ['index']];
$this->params['breadcrumbs'][] =  $model->name_ru;
?>
<div class="object-update">

    <!-- TAB NAVIGATION -->
    <ul class="nav nav-tabs" role="tablist">
        <li class="active"><a href="#tab1" role="tab" data-toggle="tab">Основное</a></li>
        <li><a href="#tab2" role="tab" data-toggle="tab">Фото</a></li>
    </ul>
    <!-- TAB CONTENT -->
    <div class="tab-content">
        <div class="active tab-pane fade in" id="tab1">
            <br>
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
        <div class="tab-pane fade" id="tab2">
            <br>
            <?php include 'image.php'?>
        </div>
    </div>

</div>