backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\Category;
use common\models\MyObject;
use common\models\ObjectImage;
use common\models\Page;
use common\models\Project;
use common\models\ProjectImage;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /*public function beforeAction($action)
    {
        if(isset($_COOKIE['language'])) {
            Yii::$app->language = $_COOKIE['language'];
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }*/

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout = 'home';
        $categories = Category::find()->all();
        return $this->render('index', [
            'categories' => $categories
        ]);
    }

    public function actionProjects()
    {
        $model = Page::findOne(1);
        $categories = Category::find()->all();
        return $this->render('projects', [
            'model' => $model,
            'categories' => $categories,
        ]);
    }

    public function actionProject($id)
    {
        $model = Category::findOne($id);
        $projects = Project::findAll(['category_id' => $id]);
        return $this->render('project', [
            'model' => $model,
            'projects' => $projects,
        ]);
    }

    public function actionProjectDetail($id)
    {
        $model = Project::findOne($id);
        $images = ProjectImage::findAll(['project_id' => $id]);
        return $this->render('project_detail', [
            'model' => $model,
            'images' => $images,
        ]);
    }

    public function actionObjects()
    {
        $model = Page::findOne(2);
        $categories = Category::find()->all();
        return $this->render('objects', [
            'model' => $model,
            'categories' => $categories,
        ]);
    }

    public function actionObject($id)
    {
        $model = Category::findOne($id);
        $objects = MyObject::findAll(['category_id' => $id]);
        return $this->render('object', [
            'model' => $model,
            'objects' => $objects,
        ]);
    }

    public function actionObjectDetail($id)
    {
        $model = MyObject::findOne($id);
        $images = ObjectImage::findAll(['object_id' => $id]);
        return $this->render('object_detail', [
            'model' => $model,
            'images' => $images,
        ]);
    }

    public function actionStudio()
    {
        $model = Page::findOne(3);
        $categories = Category::find()->all();
        return $this->render('studio', [
            'model' => $model,
        ]);
    }
}

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */

use frontend\helpers\TranslateHelper;

$this->title = Yii::$app->settings->getSetting(TranslateHelper::getLocaleCode('main_meta_t'));
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => Yii::$app->settings->getSetting('main_meta_k'),
]);
$this->registerMetaTag([
    'name' => 'description',
    'content' => Yii::$app->settings->getSetting('main_meta_d'),
]);
?>
<h3 class="main-header"><?=Yii::t('common', 1)?></h3>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <?=\frontend\widgets\FlexGridWidget::widget([
                'model' => false,
                'items' => $categories,
                'container_class' => 'categories',
                'item_class' => 'category',
                'link' => 'site/project',
                'link_item' => 'id'
            ])?>
        </div>
    </div>
</div>

frontend/views/site/object.php
<?php

/* @var $this yii\web\View */

use frontend\helpers\TranslateHelper;

$this->title = $model->meta_t ? $model->meta_t : $model->{TranslateHelper::getLocaleCode('name')};
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $model->meta_k,
]);
$this->registerMetaTag([
    'name' => 'description',
    'content' => $model->meta_d,
]);

$this->params['breadcrumbs'][] = ['label' => Yii::t('common', 'design'), 'url' => ['/site/projects']];
$this->params['breadcrumbs'][] = $model->{TranslateHelper::getLocaleCode('name')};
?>
<div class="object">

    <p><?=$model->{TranslateHelper::getLocaleCode('description')}?></p>

    <div class="page-category-container">
        <?=\frontend\widgets\FlexGridWidget::widget([
            'model' => $model,
            'items' => $objects,
            'container_class' => 'objects',
            'item_class' => 'object',
            'link' => 'site/object-detail',
            'link_item' => 'id',
            'scheme' => 'object',
        ])?>
    </div>

</div>

frontend/views/site/object_detail.php
<?php

/* @var $this yii\web\View */

use frontend\helpers\TranslateHelper;

$this->title = $model->meta_t ? $model->meta_t : $model->{TranslateHelper::getLocaleCode('name')};
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $model->meta_k,
]);
$this->registerMetaTag([
    'name' => 'description',
    'content' => $model->meta_d,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('common', 'design'), 'url' => ['/site/projects']];
$this->params['breadcrumbs'][] = ['label' => $model->category->{TranslateHelper::getLocaleCode('name')}, 'url' => ['/site/project', 'id' => $model->category_id]];
$this->params['breadcrumbs'][] = $model->{TranslateHelper::getLocaleCode('name')};
?>
<div class="object">

    <p><?=$model->{TranslateHelper::getLocaleCode('description')}?></p>

    <div class="page-category-container">
        <?=\frontend\widgets\FlexGridWidget::widget([
            'model' => $model,
            'items' => $images,
            'container_class' => 'objects',
            'item_class' => 'object',
            'link' => '',
            'link_item' => 'id',
            'scheme' => 'gallery',
        ])?>
    </div>

</div>

frontend/views/site/objects.php
<?php

/* @var $this yii\web\View */

use frontend\helpers\TranslateHelper;

$this->title = $model->meta_t ? $model->meta_t : $model->{TranslateHelper::getLocaleCode('name')};
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $model->meta_k,
]);
$this->registerMetaTag([
    'name' => 'description',
    'content' => $model->meta_d,
]);
$this->params['breadcrumbs'][] = $model->{TranslateHelper::getLocaleCode('name')};
?>
<div class="objects">

    <p><?=$model->{TranslateHelper::getLocaleCode('description')}?></p>

    <div class="page-category-container">
        <?=\frontend\widgets\FlexGridWidget::widget([
            'model' => $model,
            'items' => $categories,
            'container_class' => 'categories',
            'item_class' => 'category',
            'link' => 'site/object',
            'link_item' => 'id'
        ])?>
    </div>

</div>

frontend/views/site/project.php
<?php

/* @var $this yii\web\View */

use frontend\helpers\TranslateHelper;

$this->title = $model->meta_t ? $model->meta_t : $model->{TranslateHelper::getLocaleCode('name')};
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $model->meta_k,
]);
$this->registerMetaTag([
    'name' => 'description',
    'content' => $model->meta_d,
]);

$this->params['breadcrumbs'][] = ['label' => Yii::t('common', 'design'), 'url' => ['/site/projects']];
$this->params['breadcrumbs'][] = $model->{TranslateHelper::getLocaleCode('name')};
?>
<div class="project">

    <p><?=$model->{TranslateHelper::getLocaleCode('description')}?></p>

    <div class="page-category-container">
        <?=\frontend\widgets\FlexGridWidget::widget([
            'model' => $model,
            'items' => $projects,
            'container_class' => 'projects',
            'item_class' => 'project',
            'link' => 'site/project-detail',
            'link_item' => 'id',
            'scheme' => 'object',
        ])?>
    </div>

</div>

frontend/views/site/project_detail.php
<?php

/* @var $this yii\web\View */

use frontend\helpers\TranslateHelper;

$this->title = $model->meta_t ? $model->meta_t : $model->{TranslateHelper::getLocaleCode('name')};
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $model->meta_k,
]);
$this->registerMetaTag([
    'name' => 'description',
    'content' => $model->meta_d,
]);

$this->params['breadcrumbs'][] = ['label' => Yii::t('common', 'design'), 'url' => ['/site/projects']];
$this->params['breadcrumbs'][] = ['label' => $model->category->{TranslateHelper::getLocaleCode('name')}, 'url' => ['/site/project', 'id' => $model->category_id]];
$this->params['breadcrumbs'][] = $model->{TranslateHelper::getLocaleCode('name')};
?>
<div class="project">

    <p><?=$model->{TranslateHelper::getLocaleCode('description')}?></p>

    <div class="page-category-container">
        <?=\frontend\widgets\FlexGridWidget::widget([
            'model' => $model,
            'items' => $images,
            'container_class' => 'projects',
            'item_class' => 'project',
            'link' => '',
            'link_item' => 'id',
            'scheme' => 'gallery',
        ])?>
    </div>

</div>

frontend/views/site/projects.php
<?php

/* @var $this yii\web\View */

use frontend\helpers\TranslateHelper;

$this->title = $model->meta_t ? $model->meta_t : $model->{TranslateHelper::getLocaleCode('name')};
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $model->meta_k,
]);
$this->registerMetaTag([
    'name' => 'description',
    'content' => $model->meta_d,
]);
$this->params['breadcrumbs'][] = $model->{TranslateHelper::getLocaleCode('name')};
?>
<div class="projects">

    <p><?=$model->{TranslateHelper::getLocaleCode('description')}?></p>

    <div class="page-category-container">
        <?=\frontend\widgets\FlexGridWidget::widget([
            'model' => $model,
            'items' => $categories,
            'container_class' => 'categories',
            'item_class' => 'category',
            'link' => 'site/project',
            'link_item' => 'id'
        ])?>
    </div>

</div>

frontend/views/site/studio.php
<?php

/* @var $this yii\web\View */

use frontend\helpers\TranslateHelper;

$this->title = $model->meta_t ? $model->meta_t : $model->{TranslateHelper::getLocaleCode('name')};
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $model->meta_k,
]);
$this->registerMetaTag([
    'name' => 'description',
    'content' => $model->meta_d,
]);
$this->params['breadcrumbs'][] = $model->{TranslateHelper::getLocaleCode('name')};
?>
<div class="object">

    <p><?=$model->{TranslateHelper::getLocaleCode('description')}?></p>
    <?=\frontend\widgets\ContactWidget::widget();?>
    <br>

    <iframe height="440" src="https://maps.google.com/maps?width=700&amp;height=440&amp;hl=ru&amp;q=<?=Yii::$app->settings->getSetting(TranslateHelper::getLocaleCode('address'))?>+(dorn)&amp;ie=UTF8&amp;t=&amp;z=18&amp;iwloc=B&amp;output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
</div>